packageExtensions:
  '@storybook/core-common@7.0.12':
    dependencies:
      '@storybook/react-webpack5': ^7.0.12
  eslint-config-react-app@7.0.1:
    peerDependencies:
      '@typescript-eslint/eslint-plugin': ^5.20.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-3.6.1.cjs
